### ISSUE TITLE
Required Control: No. 5, AC-17, Remote Access

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#104]

**Comment by arcbeckman** [comment]
Given it is a cloud-based system, how would you define Remote Access?

**Comment by edward-mcclure** [comment]
As FTEs are cut more and more, many agencies become more reliant on volunteer help. For example, most National Park Service libraries are supported by off-site volunteers who catalog new materials. They are not eligible for access to our VPN because they are not employees, but need privileged access to our Integrated Library System. Would https be adequate security in such a low-risk system?

**Comment by FedRAMP** [comment]
Thank you for your question. "Remote access" here refers to the remote access technology typically associated with remote administration, such as remote desktop or SSH. If the system is accessed remotely, all requirements stand. HTTPS is outside the scope of this requirement.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
