### ISSUE TITLE
Step 1 - Question 5: Is the cloud service low-security-impact, according to the FIPS 199 definition?

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#109]

**Comment by collabarchitect** [comment]
For sake of clarity and continuity between different NIST Standards, suggest considering adopting the SP 800-171 (http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-171.pdf), Protecting Controlled Unclassified Information. As I understand it FedRAMP Tailored, it is mostly leveraging FedRAMP Low Impact. This is also similar to SP 800-171 Controls (derived from NIST SP 800-53r4, Low Impact)...  Bottom Line: Open Standards are easier to adopt...

**Comment by FedRAMP** [comment]
Thank you for your comment. NIST 800-171 explicitly defines Federal and non-Federal systems. 800-
53 is for Federal systems, and 800-171 is for non-Federal systems. The purpose of 800-171 is to provide some guidance on security controls to non-Federal systems so that sensitive government information in these non-government systems has a similar level of protection. Only Federal systems qualify for FedRAMP Tailored based on the 800-171 definition, thus 800-53 must not be used, not 800-171.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
