### ISSUE TITLE
Step 1 - Question 4: Does the cloud service provide services without requiring the collection of personally identifiable information (PII)?

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#110]

**Comment by ultrashea** [comment]
Clarification is needed regarding what qualifies as PII for this qualification - people may have differing definitions of what qualifies as PII for this requirement (i.e., does collecting username, email address, and password for authentication purposes qualify as collecting PII?)

**Comment by terrymedhurst** [comment]
Moved my earlier comment to this category:

I would very much welcome this initiative, which would accelerate the adoption of low impact collaboration applications. Having reviewed the proposed criteria for the tailored approach, I believe there should be further clarification of the PII criteria. Most collaboration applications would by their nature expect to contain basic information such as first name, last name and email address which I believe should not be an excluding factor for this approach. Perhaps as part of the implementation of this program, clear guidelines on acceptable user data can be made available.

**Comment by HHS-DVP** [comment]
@ultrashea NIST 800-60 has the information types that would make up PII.

**Comment by ultrashea** [comment]
Using the NIST 800-60 definitions, plus the definitions in NIST 800-12, it would appear that any SaaS offering that creates/uses user accounts (and collects standard information for a SaaS user account would be excluded from Tailored)

**Comment by terrymedhurst** [comment]
i think that is the heart of the issue and is problematic given one of the targeted use cases for tailored is collaboration applications.  My prior understanding was that in certain contexts an email address alone may not be considered PII - https://handbook.18f.gov/research-guidelines/#what-is-pii

**Comment by christopherdixon** [comment]
I struggle sometimes with the concept of "required" here.  If a product has structured data fields to store PII, but does not **require** the population of these fields with data to enable use of the system, does it pass this test?

**Comment by ultrashea** [comment]
One additional item that might be helpful is to provide examples of items that *might* be considered to be PII, but that are not for this qualifying question.

(i.e., if it is acceptable for a Tailored offering to collect an email address and name data from a user to create an account, that would be a good idea of an example to provide of acceptable data)

**Comment by wamalinf** [comment]
Monette joined our Breakout Room (#6) and requested that I post this use case here (Issue #110): many SaaS solutions have a 'public' module which is anonymous, i.e., does not require login, the purpose of which is to enable end-users to search, browse, discover federal information.  A use case is the 'open public access catalog' (OPAC) module of an Integrated Library System (ILS) SaaS.   

All ILS SaaS solutions have built-in functionality (requires enabling on the sysadmin side) that can provide OPAC end-users with an 'opt-in' feature that would give them added functionality, e.g.: submitting and tracking their requests for reference assistance ('My Requests'); saving search result sets for viewing at any time ('My Title Lists'), as well as being able to generate permalinks for sharing those saved result sets; saving searches for re-running at any time ('My Searches'), as well as being able to generate permalinks for sharing those saved searches; managing ones RSS feeds ('My RSS Feeds'), etc.

The 'My Account' opt-in feature requires set up of a 'Patron Record' (from the library world perspective).  This can be accomplished either through self-registration via a webform, or by the end-user emailing a request to the servicing personnel via the 'Contact Us' link on the public portal (which routes the end-users request to the fed gov agency's Google Apps email address, in the case of Dept. of the Interior).  

The added functionality enabled via setting up a 'My Account' on the public portal requires only an email address, however, email addresses are considered PII.  As a result, fed gov agencies are opting out of enabling 'opt-in' features on their ILS SaaS public portals, even though doing so would mean significant efficiency gained for the librarians providing reference service AND significant functionality for the end-users of the public portal (INCLUDING agency/other gov library info seekers).    

The reason they're opting out of enabling the 'opt-in' feature is because doing so would render their ILS SaaS an official 'System of Records' because it captures PII (i.e., the email addresses), which then comes with a long list of requirements.  And YET, the 'Contact Us' link on ALL fed gov agency public portals ALSO captures the information requester's email address (albeit in the agency's email database, behind the agency's firewall, e.g., Google Apps, in the case of Department of the Interior).  SO IRONIC!!  ;-)

**Comment by lcore** [comment]
Agree with these comments.  This is a bit of a Catch-22 and should be resolved.  Although many companies might be able to comply with FedRAMP tailored, the definition of PII for a particular agency's use-case could be a significant blocker.  It might be helpful to define up-front how the tool can be used by an agency in order to not fall into the strict categories of PII.

Ultrashea made a good point above about possible data points that need to be excluded as "PII" in some use-cases (at least I think that was the point of the comment):

"(i.e., if it is acceptable for a Tailored offering to collect an email address and name data from a user to create an account, that would be a good idea of an example to provide of acceptable data)"

**Comment by wamalinf** [comment]
Exactly, Lisa.  That's the key blocker for Tailored Baseline candidacy.
And it's so ironic, because all fed gov agency portals have a Contact Us
button (i.e., they're already getting the emails of self-directed info
seekers, i.e., provision of the email is voluntary in order for them to get
the information service).


Cheers,

Amalin

~~~~~~~~~~~~

*Everyone is entitled to his own opinion, but not his own facts*. - Daniel
Moynihan

*The good thing about science is that it's true whether or not you believe
in it*. - Neil DeGrasse Tyson

~~~~~~~~~~~~

*W. Amalin Ferguson* *| * *Team Leader, NPS Library Information Management
(LIM) Program **| Information Resources Management Directorate **|*
 415-747-8889 *|* *amalin_ferguson@nps.gov <amalin_ferguson@nps.gov>*


NPS Library Information Center <https://library.nps.gov/> (public) | NPS
LIM Program on InsideNPS <http://inside.nps.gov/library> (NPS only)

**Comment by edward-mcclure** [comment]
The linked description of PII provided by terrymedhurst above is useful. The interaction of FedRAMP Tailored, PII, and System of Records rules may be the most difficult part of implementing FedRAMP Tailored in systems for agencies that interact with non-employees. A meta-concern is that this interaction will be so complex that agencies will just walk away. Who, other than the using agency, is going to enforce these rules?

**Comment by FedRAMP** [comment]
Thank you for your comments. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's AO will always have the final decision.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
