### ISSUE TITLE
Step 1 - Question 3: Is the cloud service a Software-as-a-Service (SaaS), rather than Infrastructure-as-a-Service (IaaS) or a Platform-as-a-Service (PaaS)?

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#111]

**Comment by JuniperChad** [comment]
Our solutions are considered a SaaS. What is the intent of having this as a scoping question?

**Comment by edward-mcclure** [comment]
I suspect that over time the lines between SaaS, IaaS, and PaaS will blur. We need to express this question at an operational level, rather than relying on terminology that may soon be obsolete.

**Comment by FedRAMP** [comment]
Thank you for your comment. FedRAMP Tailored was created because many small SaaS applications were identified across the government as being useful except for the cost/resources associated with the security assessment. FedRAMP Tailored is designed to offer a more streamlined approach to authorization for these low-risk SaaS systems. While we agree the lines between SaaS, Infrastructure  as a Service (IaaS) and Platform as a Service (PaaS) may blur, FedRAMP will adjust to those changes as they occur.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
