### ISSUE TITLE
Step 1 - Question 2: Is the cloud service fully operational?

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#112]

**Comment by ultrashea** [comment]
This may represent a challenge for some CSPs who may not feel that they are able to fund resources until they are able to book revenue.

**Comment by JuniperChad** [comment]
Yes, our services run on the major CSPs in their FedRAMP Moderate cloud application. I see within Federal Civilian the need to move to FedRAMP High not necessary.

**Comment by katielewin** [comment]
What does "fully operational" mean?  Is there a reference for that term?

**Comment by jdore** [comment]
There's a difference in fully operational and available capacity.  I don't think it's too much to ask for a CSP to have the service available even if capacity isn't available pre award.

**Comment by JTRFedRAMPHHS** [comment]
Agencies would still want to know if it's a fully operational system. But it would be interesting to allow agencies to leverage FedRAMP tailored for a proof of concept system.

**Comment by RWCIT** [comment]
Was the intent here to keep the risk inherent in a system being developed out of the scope of FedRAMP Tailored?  
That was my assumption, but it seems most of the comments so far are related to service availability and capacity.

**Comment by FedRAMP** [comment]
Thank you for your comment. While we recognize CSPs are faced with a challenge in gaining customers for non-operational systems, FedRAMP was previously overwhelmed with assessments on non-operational systems. This dramatically prolonged the assessment time required for all systems. In order to ensure our accelerated assessment time, we are forced to focus our resources on operational systems. Further, we have consistently found assessments of non-operational systems do not reflect the final operational state of a system. In order to ensure the viability of an assessment, it must be performed on an operational system.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
