### ISSUE TITLE
Step 1 - Categorize Information System

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#114]

**Comment by pamcarpenterva** [comment]
Does the cloud service provide services without requiring the collection of personally identifiable information (PII)....comment is - please provide a better definition of "collection of PII"....

**Comment by JTRFedRAMPHHS** [comment]
•	Currently the FedRAMP tailored program targets systems with Low CIA (confidentiality, integrity, and availability. What happens to the ATO of the system if something changes in the environment and the system becomes moderate? 
o	Will the system have to undergo a full FedRAMP assessment?
o	Are there any check s put in place to ensure that this does not happen?

**Comment by JTRFedRAMPHHS** [comment]
•	HHS is having a hard time thinking of a cloud services that would meet the bar of being a Low, Low, Low system. Does FedRAMP have a service in mind that could serve as the initial use case?
o	HHS is unsure if agencies would want to use a service with low availability.
o	To make FedRAMP tailored more usable, the FedRAMP PMO may consider raising the bar to allow systems with at least one of the CIA triad to be moderate (M, L, L; L, M, L; or L, L, M).

**Comment by JuniperChad** [comment]
Juniper Networks currently has a UTM solution which runs in a FedRAMP moderate cloud called Sky ATP. It detects zero-day malware and sends it to the cloud where it goes through AV, then static and behavioral analytics. the whole process of detection of the zero-day malware is 2 seconds to protection in 7-1/2 minutes. This can either run on top of a next-gen firewall (SRX) or a virtual application (vSRX)

**Comment by eric2525** [comment]
We use FIPS-199 system categorization as listed in FedRAMP tailored with guidance from NIST SP800-37 and also guidance categorization from NIST SP800-60 for confidentiality, integrity, and availability (C-I-A) to High, Moderate, or Low classifications. My question is this exercise is done by the CSP, so what is the qualifying step to this or who owns this qualifying step?

**Comment by eric2525** [comment]
Also as a followup, does this have to be a Low categorization for FedRAMP Tailored to all three - Confidentiality, Integrity, and Availability?

**Comment by JTRFedRAMPHHS** [comment]
Yes, currently it has to be Low for CIA, all three elements. FedRAMP uses a high watermark so if it was L,M,L it would be a moderate system.

**Comment by marthaakalu** [comment]
Do we need a Fedramp approval of our system categorization? We are an IA consultant for federal agencies going through the RMF Assessment and Authorization process.

**Comment by minime1022** [comment]
@marthaakalu To my knowledge, you need to get approval of your FIPS 199 (system categorization) from the Agency you are receiving an authorization from.  It's Federal Data that would be going into your system; the gov owns that data, and they need to make a determination/approval of what system categorization level it needs to be at.

**Comment by JTRFedRAMPHHS** [comment]
It would be very easy for a L,L,L system to become a moderate system. I think the risk impact level would need to be reviewed on a regular basis to ensure that the CSP is still meeting that bar.

**Comment by tdafoe** [comment]
Shared responsibility - both that CSP continues to meet the bar, and that the system continues to be operated / processes information within the L,L,L constraint.

**Comment by FedRAMP** [comment]
Thank you for your comment. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's AO will always have the final decision.

Regarding the potential for the system to increase in sensitivity, this can happen with any system. It typically happens when the sensitivity of the information within the system changes rather than anything related to the functionality of the system. As with any system, if the sensitivity needs to change, a new ATO needs to be granted under the appropriate ATO process. In this case, the agency would need to issue a Moderate ATO under their process, and would then have the option to pursue a FedRAMP Agency Moderate ATO. One reason every system undergoes an annual assessment is to  ensure the system is still authorized at an appropriate level of sensitivity.

The FIPS-199 level is based largely on the information within the system, and the systems’ importance to a given agency's mission. As such, a CSP's attempt to identify the FIPS-199 level would be conjecture. As a CSP may only pursue Tailored with actual Agency customers, the CSP should work with the Agency to understand the appropriate FIPS-199 level for the system.

The Agency AO approves the categorization; however, FedRAMP will cite inconsistencies if we believe the level is not consistent with other agency definitions

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
