### ISSUE TITLE
Authority

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#116]

**Comment by tdafoe** [comment]
Editorial: "... Government data with low impact for loss _or_ confidentiality, integrity, and availability" may have been intended to read "... Government data with low impact for loss _of_ confidentiality, integrity, and availability". Suggest change to "_or_ availability" as used in FIPS 199.

**Comment by pamcarpenterva** [comment]
it needs to be very clear to agency ATO'ing a cloud solution what the very specific criteria for Fedramp tailored.    In addition, it needs to be very clear in the policy what the purchasing agency's role is.   For example, for FedRamp Tailored, would it be the plan that a solution would receive a FedRamp Tailored authorization from an Agency Sponsor and then a purchasing agency would confirm the ATO for their specific agency.

**Comment by JBitzer** [comment]
Following up on pamcarpenter's thread, since a goal of FedRAMP Tailored is to promote and accelerate the use of clouds within the Gov't, it should be made quite clear what exactly are the roles and responsibilities of the Agency personnel.  What ate they expected to execute, review, perform  - is it a one time effort or multiple instances.  Is it the review of self attestation? the validation of controls?  who is declaring a vendor's cloud offering to be "ready"

**Comment by collabarchitect** [comment]
JAB vs. Agency Specific Authorization:  Since the categorization IAW FIPS 199, specifically determining PII is an Agency per Agency decision, suggest we encourage FedRAMP Tailored candidate systems to pursue Agency specific ATOs. Although, it would be interesting if two or more Agencies determine there's no PII or the level of PII is acceptable, then perhaps JAB would make sense...

**Comment by collabarchitect** [comment]
Please see comment on adopting 800-171 Controls in Issue #109 Thanks!

**Comment by edward-mcclure** [comment]
Who checks up on the agencies? What if a weak agency approves a CSP's service, then that CSP offers its service to other agencies as "approved"? What can we do to maintain standards across agencies without imposing time/cost penalties?

**Comment by jbjonesjr** [comment]
_Hi! I work for GitHub, but I also did Govt IT for over a decade prior. These comments are in my personal capacity_

@edward-mcclure I would ask is this different than the current posture? Agencies are at present free to assess their own tools and uses, independent of other agency opinions. Since Tailored is defined as an approval at the Agency level only, is this not similar? 

To your second question about maintaining standards, I would hope the final version of the Tailored specification would include better guidance on the final templates, currently listed as _in development._ This will hopefully address our concerns.

**Comment by monetter** [comment]
What organizations have vetted FedRAMP Tailored and concur with its baseline and approach to authorization?  If agencies implement FedRAMP Tailored for low impact applications, will they be required to "defend" their use of FedRAMP Tailored to any of these organizations?

**Comment by FedRAMP** [comment]
Thank you for your comment. FedRAMP Tailored is only for FedRAMP Agency ATOs. There is no Joint Authorization Board (JAB) Provisional Authorization to Operate (P-ATO) option at this time, nor is one planned.

NIST 800-171 explicitly defines “Federal” and ”non-Federal” systems. 800-53 is for Federal systems, and 800-171 is for non-Federal systems. The purpose of 800-171 is to provide some guidance on security controls to non-Federal systems so that sensitive government information in these non-government systems have a similar level of protection. Only Federal systems qualify for FedRAMP Tailored based on the 800-171 definition, thus 800-53 must be used, not 800-171.

Each Agency's AO is free to grant or deny an ATO for any system. It is ultimately incumbent on the leveraging Agency's AO to decide whether the initial agency's ATO is sufficient for re-use. FedRAMP also performs a review of any FedRAMP Agency ATO to ensure compliance

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
