### ISSUE TITLE
FedRamp Tailored - What's not to like?

### ISSUE THREAD

**Issue by cvcook** [GSA/fedramp-tailored#119]
FedRamp Tailored appears to be a potentially great overall program by the government. A recognition that the original FedRamp scope does indeed require some tailoring to allow for additional candidate services that meet the new streamlined criteria. Implementation of FedRamp Tailored could have a profound and positive effect on both the candidate companies (vendors) and the agencies seeking to consume those services in a timely manner.

**Comment by mgrim1** [comment]
Reducing the Security requirements.

**Comment by MariaHorton** [comment]
Provides a new venue for CSPs and 3PAOs to meet, interact and offer innovation to Agencies.

**Comment by zareesinger** [comment]
Expand the marketplace of cloud providers!

**Comment by JTRFedRAMPHHS** [comment]
It could provide a way to allow the use of smaller cloud services and also provide visibility into cloud services that might be in use but not reported.

**Comment by terrymedhurst** [comment]
Pragmatic approach to accelerate adoption of low risk cloud applications.

**Comment by rgaitonde** [comment]
•	HHS is having a hard time thinking of a cloud services that would meet the bar of being a Low, Low, Low system. Does FedRAMP have a service in mind that could serve as the initial use case?
o	HHS is unsure if agencies would want to use a service with low availability.
o	To make FedRAMP tailored more usable, the FedRAMP PMO may consider raising the bar to allow systems with at least one of the CIA triad to be moderate (M, L, L; L, M, L; or L, L, M).

**Comment by collabarchitect** [comment]
I'm wrestling with Step #1, Categorization IAW FIPS 199. Who actually makes that decision and how are they basing it?

**Comment by druboi31779** [comment]
Since RARs have been introduced for Moderate and High, I am assuming that a tailored RAR would also be required here. Is this the case?

**Comment by soalab-bah** [comment]
What level of privacy sensitive info can be put on a LLL cloud environment? just wondering...

**Comment by HHS-DVP** [comment]
@collabarchitect The FIPS 199 is based off of the NIST 800-60 information types in the system, and the determination is made by the CSP. However, the authorizing agency would still have to agree on everything prior to authorizing / use I would think, similar to how it is now...

**Comment by mkburton** [comment]
@rgaitonde 
One example of a potential candidate system is library automation software. Although there are some systems with lots of features that introduce risk (e.g. users being able to log in), lots of fed libraries use a simple software that is read-only and does not collect PII. FedRAMP Tailored sounds like a good way to review and authorize the system without incurring time and money costs (associated with stricter requirements) that are not commensurate with the risk and/or the cost of the system itself.

**Comment by jrkiesel** [comment]
WRT smaller cloud services...many larger CSPs struggle to find value when they have to bring supporting applications and services in-house and/or redesign their product because those supporting services are not willing to spend the $ to be FedRAMP authorized. Having a cheaper and faster path for authorization would provide additional value to many CSPs along the supply chain.

**Comment by wamalinf** [comment]
As Malia Burton of BLM has pointed out, a use case of a Low-Impact SaaS is the proprietary Integrated Library System (ILS) SaaS category of software offered by vendors who typically contract out the hosting services to a CSP (in some, but not all cases, the CSP contracted by an ILS SaaS vendor has a FedRAMP IaaS P-ATO at the Low or Moderate Impact Level).  The ILS SaaS category of software IS an 'enterprise' solution, however, from the fed gov agency POV, it is NOT mission-critical, nor does it collect 'sensitive' information (in the way that fed gov librarians elect to implement the application).  In order to bypass requirements related to protecting the agency's 'sensitive' data (such as financial account numbers) and PII, fed gov librarians typically do NOT use the ILS SaaS Acquisition or Circulation modules that come with the typical ILS package.  In addition, the Online Public Access Catalog (OPAC) module -- which fed gov staff and partners, as well as the public, use to research library materials  -- does NOT require a login, i.e., no PII collected.   As such, the ILS SaaS category of software is a perfect candidate for Tailored Baseline, IMHO.

**Comment by JBitzer** [comment]
here's a LIKE - might be in wrong place but I do like that FedRAMP Tailored provides an easier entrance "ramp" where by an agency can either move an on premise software application solution into a cloud-based use - many SW vendors are offering both options - premise or cloud - of the same solution.  this allows an agency to try, to pilot, to begin in one department and if it works well for them to move it into an enterprise or agency-wide use as well as possibly depending on the security controls, even move to a FedRAMP moderate offering.  The challenge of moving from premise to cloud may be perceived as hard but I see FedRAMP Tailored accelerating adoption.

**Comment by jbjonesjr** [comment]
_Hi! I work for GitHub, but I also did Govt IT for over a decade prior. These comments are in my personal capacity and represent my employer_

We are very excited to see the FedRAMP office expanding their offerings to better meet the needs (and posture) of modern SAAS/cloud companies. The Government can continue to improve it's IT capabilities by embracing the best technologies for the task, cloud or otherwise, while not sacrificing security.

Great job so far, FedRAMP team!!

**Comment by FedRAMP** [comment]
Thank you for your feedback. We are adding samples and use cases to the supporting documentation and training materials.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
