### ISSUE TITLE
Low(confidentiality), Low(integrity), Low(availability Baseline in FIPS 199

### ISSUE THREAD

**Issue by Kaiiz** [GSA/fedramp-tailored#121]
I looked at some of the questions on GitHub and I see some questions revolving around low, low, low baseline. What is it?

To arrive at the LISaaS Solution the definition of a low, low, low baseline as Defined in FIPS 199 =

The potential impact is LOW if— − 
The loss of confidentiality, integrity, or availability could be expected to have a LIMITED ADVERSE AFFECT on organizational operations, organizational assets, or individuals.

AMPLIFICATION: A limited adverse effect means that, for example, the loss of confidentiality, integrity, or availability might: (i) cause a degradation in mission capability to an extent and duration that the organization is able to perform its primary functions, but the effectiveness of the functions is noticeably reduced; (ii) result in minor damage to organizational assets; (iii) result in minor financial loss; or (iv) result in minor harm to individuals.

then,

FedRamp "Tailored"  the low, low, low  Baseline Security Controls to their "Cloud  Specifications" to arrive at the  LISaaS Solution.

**Comment by MariaHorton** [comment]
The FIPS issue is something that has the potential to create questions and snags for CSPs and the 3PAOs especially where the CSP may want to accomplish Tailored Baseline instead of Moderate baseline.  One example is when Agencies previously had the opportunity to not accomplish C&A if the system was designated Low, Low, Low.  Many agencies would move systems into Low, Low, and Low to reduce costs and issues.  The CSPs are looking for speed and for lower costs.  To assist the CSPs and 3PAOs, I recommend the following:
- Provide a clear definition, include the extent of scope of the cloud applicaiton
- Establish standard examples for CSPs and 3PAOs. 
keep in mind that re-starting and re-designating systems cost both time and money.  This should match the example given in FedRAMP Weekly November 9, 2016.

**Comment by JTRFedRAMPHHS** [comment]
I think the problem with L,L,L is that for many agencies, any sort of data close to PII or that could be PII in aggregate would bump the system to a moderate in at least one element in the CIA triad.

**Comment by Kaiiz** [comment]
FIPS Categorization and associated Baseline is a Starting Point for a
minimum requirement of security controls required. From the Starting Point,
tailoring activities start, for example, tailored to Cloud Computing.
800-53 Rev. 4 controls are not specific to cloud, they are specific to the
categorization of the data and its associated security control baseline
that protects that category of data. It is all about protecting the data,
always. 800-53 rev. 4 describes tailoring in-depth.

**Comment by FedRAMP** [comment]
Thank you for your comment. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's Authorizing Official (AO) will always have the final decision.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
