### ISSUE TITLE
IAAS question

### ISSUE THREAD

**Issue by mgrim1** [GSA/fedramp-tailored#123]
Does a company need any type of Certifications for doing service work on a FEDRAMP network?

Mike Grim
Media temple

**Comment by JTRFedRAMPHHS** [comment]
•	FedRAMP tailored requires that the system uses FedRAMP authorized infrastructure. FedRAMP may want to consider limiting the infrastructure to CSP’s with a JAB P-ATO. Since the system using the tailored baseline is self-attesting to the implementation of controls, including inherited controls, systems with a JAB P-ATO would allow the agency to more easily access their continuous monitoring documentation to provide an additional insight into the system.

**Comment by Wynsome** [comment]
I think The FedRAMP requirements for the use of FedRAMP authorized Infrastructure is a sound and logical one.  The IaaS sits at the bottom of any implementation of cloud.  While not all CSOs neatly fits into the standard layered service models,  I believe it is paramount that these infrastructures are already assessed, authorized and are being monitored.  It will help other CSPs with PaaS and SaaS CSO as well as the CSC to understand the security risks since the documentation of these risks are already identified.

**Comment by FedRAMP** [comment]
Thank you for your comment. FedRAMP Tailored is focused on low impact software as a service (LI-
SaaS) systems leveraging existing infrastructure that is already FedRAMP-authorized. The approved System Security Plan (SSP) and configuration management (CM) process for the leveraged system address maintenance requirements. A LI-SaaS that fits the criteria for FedRAMP Tailored should not be involved with the service of a FedRAMP network.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
