### ISSUE TITLE
Third Party Authentication / ID Management Service Could Provide a Way Around the PII/Account Issue

### ISSUE THREAD

**Issue by JTRFedRAMPHHS** [GSA/fedramp-tailored#128]
If you used a service like Login.gov to authenticate, the Cloud Service/ SaaS would not need to store PII (name, email, etc) to authenticate and create an account for the user.

**Comment by jbjonesjr** [comment]
@JTRFedRAMPHHS that is true for authentication, but many SAAS services will still want to send an email to their users for various interactions. Combine that email with a name, and you'll get to PII.

As defined, it's going to be very hard to prevent most systems from dealing in PII.

**Comment by seanru** [comment]
what risk level of PII does first name, last name, and email constitute?

**Comment by JTRFedRAMPHHS** [comment]
@seanru It would be at least a moderate in general.

**Comment by seanru** [comment]
"―The potential impact is LOW if the loss of confidentiality, integrity, or availability could be
expected to have a limited adverse effect on organizational operations, organizational assets, or
individuals. A limited adverse effect means that, for example, the loss of confidentiality,
integrity, or availability might (i) cause a degradation in mission capability to an extent and
duration that the organization is able to perform its primary functions, but the effectiveness of the
functions is noticeably reduced; (ii) result in minor damage to organizational assets; (iii) result in
minor financial loss; or (iv) result in minor harm to individuals."

That is direct from NIST SP 800-122. It seems as though it's a bit of a gray area. Burden of proof may rest upon the usage of the product... but is the SaaS product/vendor inheriting the risk of the email account/provider being compromised? or access to the SaaS product being compromised?

**Comment by seanru** [comment]
Further, another factor affecting the risk should be the agency's usage (or non-usage) of the product. For example, agencies A+B are both using a SaaS product. 

Agency A chooses to populate all user data fields to include things like address, phone number, place of employment, in addition to first name, last name, email etc...

Agency B chooses to populate only first name, last name and email and the SaaS product allows for removal of access to all other user data fields and leave those fields empty since they could be considered PII at higher risk level if populated. This is done to minimize risk.

The risk assigned to the usage of the SaaS product should be different, should it not?

**Comment by FedRAMP** [comment]
Thank you for this useful suggestion. We incorporated this into the latest revision, except we did not explicitly call out ‘login.gov.’ Instead, we suggested using an external directory covered by an existing ATO. Once authorized, ’login.gov’ will mimic other agencies’ use of AD and LDAP solutions.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
