### ISSUE TITLE
Editorial and Presentation Comments

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-tailored#165]
Please leave comments related to editorial issues here. Comments left here should focus on grammar, spelling, formatting, and presentation issues, including suggestions for improving presentation.

**Comment by Ray-B** [comment]
From Appendix B

> 11.1 HARDWARE INVENTORY
> 
> Use the FedRAMP Inventory Workbook to list the principal hardware components for <Information System Abbreviation>.  
> Note: A complete and detailed list of the system hardware and software inventory is required per NIST SP 800-53, Rev 4 CM-8.

NIST references are nice, but why are we making everyone cross reference? If FedRAMP is going through the work of providing revision specific references include the bloody link to the NIST PDF so I can save time.

**General Comment**

> Instruction: In the sections that follow, fully describe how the information security control is implemented in the system.  All controls originate from a system or from a business process. It is important to describe where the control originates from so that it is clear whose responsibility it is to implement, manage, and monitor the [...]

The instructions in many cases take up more space in the document that some of the replaceable content that needs to be documented / submitted. You can _Find and Replace_ / Regex out the instructions, but it would be much easier if instead of injecting instructions inside of the templates, that they are separated logically. I spend more time cutting, copying and pasting stuff in and out of templates and trying to organize it into something presentable than anything else.

**Comment by FedRAMP** [comment]
Thank you for your feedback. We are evaluating the incorporation of links where appropriate. This may not be complete for all links time for the official release of FedRAMP Tailored, and will be more fully addressed in subsequent revisions. 

Regarding the inclusion or separation of instructions, we have found more authors prefer to have the instructions at the point of use rather than in a separate document. More importantly, we find a much higher degree of compliance with the instructions if they are at the point of use. 

We continue to look at methods to allow for easy removal of instructions. For example, all the instructions are formatted with a specific Word style, which is different from the rest of the document. MS Word provides the ability to “Select all text with similar formatting”, which enables swift highlight and deletion of all instructional text. (See https://support.office.com/en-us/article/Select-a-shape-or-other-object-8db4e2f6-873a-46a7-87cb-fbb998a1f955#bm3 )
