### ISSUE TITLE
Appendix B - FedRAMP Tailored Template

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-tailored#169]
Please leave comments and have discussions here related to the FedRAMP Tailored Template defined in Appendix B.

**Comment by Ray-B** [comment]
10.4 NETWORK ARCHITECTURE and 11 SYSTEM ENVIRONMENT 

Some awkward wording in the context of typical cloud environment.

**Examples**

>  Assessors should be able to easily map hardware, software, and network inventories back to this diagram. 

Would it be more clear to use language that more accurately maps to cloud concepts? Instead of just brick and mortar network inventories, we should also be talking about scaling policies. What are the constraints on inventory? Most cloud instances in something like a micro-service architecture are going to be ephemeral, and it's important for an assessor to recognize this rather than acting both surprised and concerned. This is a natural state of cloud. This exact issue has come up during our FedRAMP certification - significant time was spent trying to explain our particular ephemeral inventory to the auditors / assessors, and then assisting in effectively mapping that knowledge back to the FedRAMP requirements. 

> The logical network topology is shown in Figure 10-2, Network Diagram, mapping the data flow between components. 

Can we be more specific here about what constitutes data-flow? What about data-flows that are contingent on SaaS or PaaS features being activated or deactivated? How to we explain cases where new data flows may be created when features are added? 

_Moved additional comments to different sections._

**Comment by FedRAMP** [comment]
Thank you for your feedback. Your concerns are valid. FedRAMP is updating our guidance across the program for architecture diagrams, network topology diagrams, as well as related inventory management and associated vulnerability management. As we finalize this guidance, we will revisit all appropriate FedRAMP diagrams, including FedRAMP Tailored. We are incorporating your feedback into that effort.
