### ISSUE TITLE
More details on the PII stipulation.

### ISSUE THREAD

**Issue by DK1999** [GSA/fedramp-tailored#28]
I would be interested in more detail on: 

4) Does the cloud service provide services without requiring the collection of personally identifiable information (PII)?

What counts as PII?  For example, does the option to sign up for an account  with an email address constitute "requiring PII?"  Examples would help.  Thanks!

**Comment by afeld** [comment]
> What counts as PII?

* http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-122.pdf#page13
* https://handbook.18f.gov/research-guidelines/#what-is-pii

Good call that it should link somewhere!

**Comment by wamalinf** [comment]
Many SaaS solutions have a 'public' module which is anonymous, i.e., does not require login, the purpose of which is to enable end-users to search, browse, discover federal information.  A use case is the 'open public access catalog' (OPAC) module of an Integrated Library System (ILS) SaaS.   

All ILS SaaS solutions have built-in functionality (requires enabling on the sysadmin side) that can provide OPAC end-users with an 'opt-in' feature that would give them added functionality, e.g.: submitting and tracking their requests for reference assistance ('My Requests'); saving search result sets for viewing at any time ('My Title Lists'), as well as being able to generate permalinks for sharing those saved result sets; saving searches for re-running at any time ('My Searches'), as well as being able to generate permalinks for sharing those saved searches; managing ones RSS feeds ('My RSS Feeds'), etc.

The 'My Account' opt-in feature requires set up of a 'Patron Record' (from the library world perspective).  This can be accomplished either through self-registration via a webform, or by the end-user emailing a request to the servicing personnel via the 'Contact Us' link on the public portal (which routes the end-users request to the fed gov agency's Google Apps email address, in the case of Dept. of the Interior).  

The added functionality enabled via setting up a 'My Account' on the public portal requires only an email address, however, email addresses are considered PII.  As a result, fed gov agencies are opting out of enabling 'opt-in' features on their ILS SaaS public portals, even though doing so would mean significant efficiency gained for the librarians providing reference service AND significant functionality for the end-users of the public portal (INCLUDING agency/other gov library info seekers).    

The reason they're opting out of enabling the 'opt-in' feature is because doing so would render their ILS SaaS an official 'System of Records' because it captures PII (i.e., the email addresses), which then comes with a long list of requirements.  And YET, the 'Contact Us' link on ALL fed gov agency public portals ALSO captures the information requester's email address (albeit in the agency's email database, behind the agency's firewall, e.g., Google Apps, in the case of Department of the Interior).  SO IRONIC!!  ;-)

**Comment by FedRAMP** [comment]
Thank you for your comments. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's AO will always have the final decision.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
