### ISSUE TITLE
FEDRAMP-Tailored

### ISSUE THREAD

**Issue by tubunuru** [GSA/fedramp-tailored#35]
Question:
1) Is this different from providing an Agency FEDRAMP ATO? Because this doesn't look any different.  
2) So does the agency provide justification if then they don't have to answer certain controls? 
3) Why such a tailoring for SaaS products? 
4) For such a tailoring will the process be much quicker for approval?

**Comment by FedRAMP** [comment]
Thank you for your questions. Yes, this is a FedRAMP Agency ATO. The difference is the FedRAMP Agency ATO process has focused on Moderate Impact systems and all three cloud model types. This is strictly for Low Impact SaaS systems only. We are not waiving any NIST requirements. The NIST 800-53r4 Low baseline requirements must still be satisfied. We are simply focusing the assessment activities and authorization decisions on the most compelling of those requirements, and suggesting a reduced due-diligence on the remaining requirements do not constitute a significant risk to the government due to the low impact of the system. 

There are many existing systems the government wishes to use where a more tradition assessment becomes cost-prohibitive with little added benefit. FedRAMP is most intended to address these systems.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
