### ISSUE TITLE
UK government G-Cloud 9

### ISSUE THREAD

**Issue by jbjonesjr** [GSA/fedramp-tailored#38]
Sharing for reference: The UK Government recently announced [G-Cloud 9](https://digitalmarketplace.blog.gov.uk/2017/02/13/whats-planned-for-g-cloud-9/) and have published the draft questions for their targeted lots, which focuses on:

* cloud hosting
* cloud software
* cloud support

The cloud software target would seem to be similar to what FedRAMP tailored is aiming for.  You can see the full set of questions (and what is required) in this [post](https://digitalmarketplace.blog.gov.uk/2017/02/16/sharing-service-questions-for-g-cloud-9/).

**Of note:** The questions they are asking to validate services are much lighter weight and plain-language than what has been proposed in the initial tailored draft.

**Comment by FedRAMP** [comment]
Thank you for the recommendation. The resources are interesting and useful. We are moving more toward the use of plain language as a program, which is challenging due to our reliance on legacy documents and government standards such as NIST, which are outside our scope of control. Please look for more plain-language as FedRAMP continues to evolve. If there are specific examples you feel are especially compelling, we would love to hear about them.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
