### ISSUE TITLE
Comments from fedramp@hhs.gov

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-tailored#50]
FedRAMP Tailored Comments:
•	In FedRAMP tailored, there are a set of controls that only require self-attestation on behalf of the CSP. HHS was unsure of the level of documentation required for these controls. 
o	Does the CSP only attest that the controls are in place? 
o	How does the CSP formally submit the self-attestation? Is there a single document where they sign off to self-attest?
o	 Does the CSP still need to document their implementation in the SSP but simply does not test their implementation?
o	HHS also has a concern about the level of risk acceptance need to  ATO an system that, where the CSP is allow to self-attest to the implementation and ongoing operation of a  fairly large subset of controls.
•	Currently the FedRAMP tailored program targets systems with Low CIA (confidentiality, integrity, and availability. What happens to the ATO of the system if something changes in the environment and the system becomes moderate? 
o	Will the system have to undergo a full FedRAMP assessment?
o	Are there any check s put in place to ensure that this does not happen?
•	HHS is having a hard time thinking of a cloud services that would meet the bar of being a Low, Low, Low system. Does FedRAMP have a service in mind that could serve as the initial use case?
o	HHS is unsure if agencies would want to use a service with low availability.
o	To make FedRAMP tailored more usable, the FedRAMP PMO may consider raising the bar to allow systems with at least one of the CIA triad to be moderate (M, L, L; L, M, L; or L, L, M).
•	FedRAMP tailored requires that the system uses FedRAMP authorized infrastructure. FedRAMP may want to consider limiting the infrastructure to CSP’s with a JAB P-ATO. Since the system using the tailored baseline is self-attesting to the implementation of controls, including inherited controls, systems with a JAB P-ATO would allow the agency to more easily access their continuous monitoring documentation to provide an additional insight into the system.  
•	Why does FedRAMP tailored allow for self-attestation for the creation of a POA&M (CA-5)? The CSP could simply provide the POA&M as proof. 
o	Does this mean that the CSP going through the FedRAMP tailored process is not required to maintain a POA&M for continuous monitoring?

Any questions about these comments should be directed to FedRAMP@hhs.gov

**Comment by FedRAMP** [comment]
Thank you for your comments. The controls are still documented in APPENDIX B - FedRAMP Tailored
 LI-SaaS Template, which serves as the SSP, SAP and SAR. The attestation language has been enhanced to include specific attestation statements about each control. These can be reviewed in APPENDIX E - FedRAMP Tailored LI-SaaS Self-Attestation Requirements. Appendices B and E are submitted as part of the authorization package. We still require an assessment by an external assessment entity (defined by the agency) for the most critical controls. Ultimately each Agency's AO has the latitude to accept CSP attestation or require an assessment of any or all controls.

Regarding the potential for the system to increase in sensitivity. this can happen with any system and typically happens because the sensitivity of the information within the system changes rather than anything related to the functionality of the system. As with any system, if the sensitivity needs to change, a new ATO needs to be granted under the appropriate ATO process. In this case, the Agency would need to issue a Moderate ATO under their process, and would then have the option to pursue a FedRAMP Agency Moderate ATO. One reason every system undergoes an annual assessment is to ensure the system is still authorized an appropriate level of sensitivity.

Self-attestation is about eliminating the need for the assessor to verify the requirement. APPENDIX D - FedRAMP Tailored LI-SaaS Continuous Monitoring Guide still requires monthly reporting. As this reporting will be monitored by the government, and as we are not requiring a particular POA&M format for LI-SaaS, we believe there is no need for the assessor to also look at this.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
