### ISSUE TITLE
Clarify Step 1 item 4 - about a tailored CSP "collecting data"

### ISSUE THREAD

**Issue by DXCmarilyn** [GSA/fedramp-tailored#51]
Many of the comments collected so far mention item 4 as an area of concern. (I've thumbs upped all of them)
Step 1 item 4 says "Does the cloud service provide services without requiring the collection of personally identifiable information (PII)?"
The first clarification I would make is to the wording. I would favor "Does the cloud service provide services without requiring the collection of sensitive data, for example, personally identifiable information (PII)".
The rationale is that, in my experience, there is a good deal of data that Agencies consider sensitive that is not PII. For example, some agencies maintain that a fully qualified domain name or the IP address of a government server is "sensitive data" requiring enhanced protective measures not found on a "Low" system.
Any CSP must collect a certain amount of potentially "sensitive data", including the PII of personnel at the agency with whom the CSP is conducting business, granting access, providing monitoring, or as recipients of required reporting. Likewise, most CSPs need at least some information about the system(s) connecting to their CSO. Agencies need clear guidance to ensure that the simple need to collect this type of Required Business Information by the CSO does not automatically exclude the use of a LISaaS from consideration to meet an agency's business need (as was suggested by one of the other commenters).

I would suggest that at least a footnote clarification should be made which draws a distinction between the data necessarily collected by a CSP to engage in business with a government agency ("Required Business Data"), v. data entered by, stored, or accessible to ordinary users of the CSO.

**Comment by wamalinf** [comment]
Monette joined our Breakout Room (#6) and requested that I post this use case here (Issue #110): many SaaS solutions have a 'public' module which is anonymous, i.e., does not require login, the purpose of which is to enable end-users to search, browse, discover federal information.  A use case is the 'open public access catalog' (OPAC) module of an Integrated Library System (ILS) SaaS.   

All ILS SaaS solutions have built-in functionality (requires enabling on the sysadmin side) that can provide OPAC end-users with an 'opt-in' feature that would give them added functionality, e.g.: submitting and tracking their requests for reference assistance ('My Requests'); saving search result sets for viewing at any time ('My Title Lists'), as well as being able to generate permalinks for sharing those saved result sets; saving searches for re-running at any time ('My Searches'), as well as being able to generate permalinks for sharing those saved searches; managing ones RSS feeds ('My RSS Feeds'), etc.

The 'My Account' opt-in feature requires set up of a 'Patron Record' (from the library world perspective).  This can be accomplished either through self-registration via a webform, or by the end-user emailing a request to the servicing personnel via the 'Contact Us' link on the public portal (which routes the end-users request to the fed gov agency's Google Apps email address, in the case of Dept. of the Interior).  

The added functionality enabled via setting up a 'My Account' on the public portal requires only an email address, however, email addresses are considered PII.  As a result, fed gov agencies are opting out of enabling 'opt-in' features on their ILS SaaS public portals, even though doing so would mean significant efficiency gained for the librarians providing reference service AND significant functionality for the end-users of the public portal (INCLUDING agency/other gov library info seekers).    

The reason they're opting out of enabling the 'opt-in' feature is because doing so would render their ILS SaaS an official 'System of Records' because it captures PII (i.e., the email addresses), which then comes with a long list of requirements.  And YET, the 'Contact Us' link on ALL fed gov agency public portals ALSO captures the information requester's email address (albeit in the agency's email database, behind the agency's firewall, e.g., Google Apps, in the case of Department of the Interior).  SO IRONIC!!  ;-)

**Comment by FedRAMP** [comment]
Thank you for your comments. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's AO will always have the final decision.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
