### ISSUE TITLE
Clarification of PII: from info@fedramp.gov

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-tailored#55]
I am the CEO of a software company in the DC area with a significant Federal focus. We would like to be able to offer our cloud product to the Federal government and are looking at the FedRAMP process. The proposed Tailored approach is a perfect fit for our type of application and we are looking forward to seeing this become an officially supported approach. My one area of concern is clarification of what is considered personally identifiable information. Most software applications require a login and a means to provide notification messages to the end user. This generally means we need to collect a name and an email address. If this is considered to be personally identifiable information, then I don’t believe any company will qualify for the new tailored approach. It is not clear to me whether the criteria would include a restriction on name and email address so I hope a clarification can be provided as part of the finalization of this approach. 
Regards, 
Shelly Heiden

Shelly Heiden 
CEO 
www.vbrick.com<http://www.vbrick.com>

**Comment by seanru** [comment]
I can add from the contractor side supporting the gov/military there doesn't seem to be much consistency from one organization to the next into the guidance that is provided for systems requiring username and password and public facing .gov or .mil websites.

**Comment by wamalinf** [comment]
Monette joined our Breakout Room (#6) and requested that I post this use case here (Issue #110): many SaaS solutions have a 'public' module which is anonymous, i.e., does not require login, the purpose of which is to enable end-users to search, browse, discover federal information.  A use case is the 'open public access catalog' (OPAC) module of an Integrated Library System (ILS) SaaS.   

All ILS SaaS solutions have built-in functionality (requires enabling on the sysadmin side) that can provide OPAC end-users with an 'opt-in' feature that would give them added functionality, e.g.: submitting and tracking their requests for reference assistance ('My Requests'); saving search result sets for viewing at any time ('My Title Lists'), as well as being able to generate permalinks for sharing those saved result sets; saving searches for re-running at any time ('My Searches'), as well as being able to generate permalinks for sharing those saved searches; managing ones RSS feeds ('My RSS Feeds'), etc.

The 'My Account' opt-in feature requires set up of a 'Patron Record' (from the library world perspective).  This can be accomplished either through self-registration via a webform, or by the end-user emailing a request to the servicing personnel via the 'Contact Us' link on the public portal (which routes the end-users request to the fed gov agency's Google Apps email address, in the case of Dept. of the Interior).  

The added functionality enabled via setting up a 'My Account' on the public portal requires only an email address, however, email addresses are considered PII.  As a result, fed gov agencies are opting out of enabling 'opt-in' features on their ILS SaaS public portals, even though doing so would mean significant efficiency gained for the librarians providing reference service AND significant functionality for the end-users of the public portal (INCLUDING agency/other gov library info seekers).    

The reason they're opting out of enabling the 'opt-in' feature is because doing so would render their ILS SaaS an official 'System of Records' because it captures PII (i.e., the email addresses), which then comes with a long list of requirements.  And YET, the 'Contact Us' link on ALL fed gov agency public portals ALSO captures the information requester's email address (albeit in the agency's email database, behind the agency's firewall, e.g., Google Apps, in the case of Department of the Interior).  SO IRONIC!!  ;-)

**Comment by FedRAMP** [comment]
Thank you for your comments. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's AO will always have the final decision.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
